config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]

  root 'events#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # resources :current_events, only: [:new, :create]

  post 'attend', to: 'events#attend_event'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current_event.rb
class CurrentEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :current_events
  has_many :attendees, through: :current_events, source: :user

  scope :past, -> { where 'date < ?', Date.today }

  scope :upcoming, -> { where 'date >= ?', Date.today }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  has_many :events, foreign_key: 'creator_id'
  has_many :current_events
  has_many :attended_events, through: :current_events, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :already_attendee?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def require_login
    redirect_to root_path unless logged_in?
    flash[:notice] = 'You must be logged in to perform this action'
  end

  def already_attendee?
    attendees = @event.attendees
    attendees.include?(current_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update attend_event destroy]
  before_action :require_login, only: %i[new create edit update destroy attend_event]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @attendees = @event.attendees
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def attend_event
    if !already_attendee?
      @event.attendees << current_user
      redirect_back fallback_location: :back
      flash[:notice] = 'Success!'
    else
      redirect_back fallback_location: :back
      flash[:notice] = 'You are already a member. You can only register once!'
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_username(params[:username])

    if user
      session[:user_id] = user.id
      redirect_to users_path, notice: 'Logged in'
    else
      flash.now[:alert] = 'username does not exist'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'You are logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events = @user.events
    @attended_events = @user.attended_events
    @upcoming_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.past
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :username)
  end

  def require_same_user
    redirect_to users_path if current_user != @user
    flash[:notice] = 'You cannot perform this action'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class = "row">
  <div class = "col-md-6 offset-md-3">
        <%= form_with(model: event, local: true) do |form| %>
          <% if event.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

              <ul>
              <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control', rows: 3 %>
          </div>

          <div class="form-group">
            <%= form.label :date %>
            <%= form.date_select :date, class: 'form-control' %>
          </div>

          <div class="actions">
            <%= form.submit 'Submit', class: 'btn btn-primary' %>
          </div>
        <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class = "text-center">Events</h1>
<h3 class = "text-center">Upcoming Events</h3>

<div class = "row">
    
    <% @upcoming_events.each do |event| %>
      <div class = "col-md-3 mt-3 mb-3">
        <div class="card-deck">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Event Title: <%= event.name %></h5>
              <p class="card-text">Event: <%= event.description %></p>
              <p>Event Date: <%= event.date %></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Attend this event', { :controller => 'events', :action => 'attend_event', :id => event.id }, method: :post, class: 'btn btn-default'%>
              <%= link_to 'Show', event, class: "btn btn-default" %>
            </div>
          </div>
        </div> 
    </div>
    <% end %> 

</div>
<hr>
<h3 class = "text-center">Past Events</h3>
<div class = "row">
    
    <% @past_events.each do |event| %>
      <div class = "col-md-3 mt-3 mb-3">
        <div class="card-deck">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Event Title: <%= event.name %></h5>
              <p class="card-text">Event: <%= event.description %></p>
              <p>Event Date: <%= event.date %></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Show', event, class: "btn btn-default" %>
            </div>
          </div>
        </div> 
    </div>
    <% end %> 

</div>

app/views/events/new.html.erb
<h1 class = "text-center">New Event</h1>

<%= render 'form', event: @event %>


<div class = "row">
  <div class = "col-md-6 offset-md-3">
    <%= link_to 'Back', events_path %>
  </div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<hr>
<p>
  <h3>Events Creator: <%= @event.creator.username %></h3>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<br>
<hr>
<p>
  <h3>Events Attendees</h3>

  <% @attendees.each do |attendee| %>
    <%= attendee.name %>
  <% end %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <%= link_to 'Private Events', events_path, class: 'navbar-brand'%>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              
              <li class="nav-item">
                <%= link_to "All Events", events_path, class: 'nav-link' %>
              </li>
              
              <li class="nav-item">
                <%= link_to "Users", users_path, class: 'nav-link'%>
              </li>
            </ul>

            <ul class="navbar-nav ml-auto">
              <% if !logged_in? %>
                <li class="nav-item">
                  <%= link_to 'Login', login_path, class: 'nav-link'%>
                </li>

                <li class="nav-item">
                  <%= link_to 'Sign Up', new_user_path, class: 'nav-link'%>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Create an Event', new_event_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Log Out', logout_path, class: 'nav-link' %>
                </li>

              <% end %>
            </ul>
            
          </div>
        </nav>


      <div class = "container">
        <%= yield %>

      </div>
  </body>
</html>

app/views/users/_form.html.erb
 <div class = "row">
  <div class = "col-md-6 offset-md-3 mt-5">
  
    <%= form_with(model: user, local: true) do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>



 
      <div class="form-group">
        <%= form.label :name %><br>
        <%= form.text_field :name, class: 'form-control' %><br>
      </div>

      <div class="form-group">
        <%= form.label :username %><br>
        <%= form.text_field :username, class: 'form-control' %><br>
      </div>

      <div class="form-group">
        <%= form.submit :submit, class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% if current_user == @user %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <% if logged_in? && current_user == user %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1 class = "text-center mt-5">New User</h1>

<%= render 'form', user: @user %>


<div class = "row">
  <div class = "col-md-6 offset-md-3">
    <%= link_to 'Login', login_path %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <h2>User Datails:</h2>  
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %> 
</p>

<br>
<p>
    <h3>Created Events:</h3>
  </p>
<% @events.each do |event| %>
  
  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>
  <p>
    <strong>Date</strong>
    <%= event.date %>
  </p>
  <%= link_to 'Show Event', event_path(event) %><br>

<% end %>
<hr>
<p>
  <h3>Upcoming Events to Attend</h3>
  <% @upcoming_events.each do |event| %>
    Event: <%= event.description %>
    Event Date: <%= event.date %>
  <% end %>
</p>
<hr>

<p>
  <h3>Past Attended Events</h3>
  <% @prev_events.each do |event| %>
    Event: <%= event.description %>
    Event Date: <%= event.date %>
  <% end %>
</p>



<% if logged_in? && current_user == @user %>
  <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>
<%= link_to 'Back', users_path %>

<%= link_to 'Event', event_path %>